/* Main.c file generated by Ankit PIC VS Code tool
 *
 * Created:   <Date>
 * Processor: PIC16f1877A
 * Compiler:  MPLAB XC8, Plz add in setting bin folder of xc8
 */

#include <xc.h>

#pragma config FOSC = HS // Oscillator Selection bits (HS oscillator)
#pragma config WDTE = OFF // watchdog time enable bit (WDTE disabled)
#pragma config PWRTE= OFF // Power up Timer enable bit
#pragma config BOREN = ON
#pragma config LVP = ON
#pragma config CPD = OFF
#pragma config WRT= OFF
#pragma config CP = OFF

#define _XTAL_FREQ 20000000 //20 Mhz clock




int main(void)
{
    // Write your code here

      
    while (1)
    {
    

    }

    return 0;
}  
