/* Main.c file generated by Ankit PIC-VS-Code tool
 * 
 * Created:   <Date>
 * Processor: PIC16f1877A
 * Compiler:  MPLAB XC8, Plz add in setting bin folder of xc8
 */

#include <xc.h>

#pragma config FOSC = HS // Oscillator Selection bits (HS oscillator)
#pragma config WDTE = OFF // watchdog time enable bit (WDTE disabled)
#pragma config PWRTE = OFF // Power up Timer enable bit
#pragma config BOREN = ON
#pragma config LVP = ON
#pragma config CPD = OFF
#pragma config WRT = OFF
#pragma config CP = OFF

#define _XTAL_FREQ 8000000 //20 Mhz clock

int main(void)
{
    // Write your code here
    TRISA0 = 0; // Set RA0 as output for LED
    TRISB1 = 1; // Set RA1 as input for switch

    RA0 = 0; 
    RB1 = 0;
    
    while (1) // Continuous loop
    {
        if(RB1 == 0){ // Pull Up resitor used
            RA0 = 1;  // LED ON
        }
        else{
            RA0 =0 ; // LED OFF
        }
    }

    return 0;
}
